# Generated by Django 6.0.3 on 2026-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="released",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
